apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: datalake-query-ingester-configmap
    literals:
      - DATALAKEQUERYINGESTER_KAFKA_TOPIC=
      - KAFKA_BROKERS=